# Generated by Django 3.2.8 on 2021-10-16 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('descripttion', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('banner_image', models.ImageField(upload_to='upload/banners/')),
                ('heading1', models.CharField(blank=True, max_length=35, null=True)),
                ('heading2', models.CharField(blank=True, max_length=35, null=True)),
                ('heading3', models.CharField(blank=True, max_length=35, null=True)),
                ('element_1_html', models.CharField(blank=True, max_length=100, null=True)),
                ('element_2_html', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('javascript', models.TextField(blank=True, null=True)),
                ('css', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('file_to_share', models.FileField(upload_to='upload/files/')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('logo_small', models.ImageField(blank=True, null=True, upload_to='uploads/company/')),
                ('logo_big', models.ImageField(blank=True, null=True, upload_to='uploads/company/')),
                ('favicon_icon', models.ImageField(blank=True, null=True, upload_to='uploads/company/')),
                ('contact_number1', models.CharField(max_length=15)),
                ('contact_number2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line3', models.CharField(blank=True, max_length=50, null=True)),
                ('map_location', models.TextField(blank=True, null=True)),
                ('fb_link', models.CharField(blank=True, max_length=50, null=True)),
                ('insta_link', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=50, null=True)),
                ('establishment_year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('customer_photo', models.ImageField(upload_to='upload/customer/')),
                ('company_name', models.CharField(max_length=20)),
                ('compnay_logo', models.ImageField(upload_to='upload/company/')),
                ('customer_comment', models.CharField(max_length=100)),
                ('show_logo_in_client_list', models.BooleanField(default=False)),
                ('show_testimonials', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('banner_image', models.ImageField(upload_to='upload/banners/')),
                ('category_tag', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Our_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('person_image', models.ImageField(upload_to='upload/team/')),
                ('designation', models.CharField(max_length=25)),
                ('contact_number', models.CharField(max_length=15)),
                ('mail_id', models.EmailField(max_length=254)),
                ('facebook_profile_link', models.URLField()),
                ('linked_in_profile_link', models.URLField()),
                ('skype_profile_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Our_values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('icom_image', models.ImageField(blank=True, null=True, upload_to='upload/icons/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/images/')),
                ('value', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hsn', models.CharField(max_length=10)),
                ('mrp', models.FloatField()),
                ('image1', models.ImageField(upload_to='upload/product/')),
                ('image2', models.ImageField(upload_to='upload/product/')),
                ('image3', models.ImageField(upload_to='upload/product/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions_and_answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quetion', models.CharField(max_length=25)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Requests_for_quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('subject', models.CharField(default='Request for quote', max_length=30)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='News_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.news')),
            ],
        ),
    ]
