# Generated by Django 3.2.8 on 2021-10-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='brochure',
            options={'verbose_name_plural': 'Brochures'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Company'},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name_plural': 'Customer'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='news_comment',
            options={'verbose_name_plural': 'News Comment'},
        ),
        migrations.AlterModelOptions(
            name='our_team',
            options={'verbose_name_plural': 'Our Team'},
        ),
        migrations.AlterModelOptions(
            name='our_values',
            options={'verbose_name_plural': 'Our Values'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='questions_and_answers',
            options={'verbose_name_plural': 'Q&A'},
        ),
        migrations.AlterModelOptions(
            name='requests_for_quote',
            options={'verbose_name_plural': 'Request for Quatation'},
        ),
        migrations.AddField(
            model_name='company',
            name='GSTIN',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
