# Generated by Django 3.2.8 on 2021-10-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_map_address_written'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='map_address_written',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
