# Generated by Django 3.2.8 on 2021-10-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_company_map_address_written'),
    ]

    operations = [
        migrations.RenameField(
            model_name='our_values',
            old_name='icom_image',
            new_name='icon_image',
        ),
    ]
