# Generated by Django 3.2.8 on 2021-10-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_icom_image_our_values_icon_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_us',
            old_name='descripttion',
            new_name='description',
        ),
    ]
