# Generated by Django 3.2.8 on 2021-10-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_descripttion_about_us_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='testimonials',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
