# Generated by Django 3.2.8 on 2021-10-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211017_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='testimonials',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
