# Generated by Django 3.2.8 on 2021-10-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211017_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
