# Generated by Django 3.2.8 on 2021-10-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_news_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='show_in_home_page',
            field=models.BooleanField(default=False),
        ),
    ]
