# Generated by Django 3.2.8 on 2021-10-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_news_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_us',
            old_name='image',
            new_name='image_main1',
        ),
        migrations.AddField(
            model_name='about_us',
            name='image_main2',
            field=models.ImageField(blank=True, null=True, upload_to='upload/images/'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='image_main3',
            field=models.ImageField(blank=True, null=True, upload_to='upload/images/'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='image_sub1',
            field=models.ImageField(blank=True, null=True, upload_to='upload/images/'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='image_sub2',
            field=models.ImageField(blank=True, null=True, upload_to='upload/images/'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='image_sub3',
            field=models.ImageField(blank=True, null=True, upload_to='upload/images/'),
        ),
    ]
