# Generated by Django 3.2.8 on 2021-10-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20211018_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Why_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('fa_icon', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Why Us',
            },
        ),
    ]
