# Generated by Django 3.2.8 on 2021-10-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_why_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='why_us',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
