# Generated by Django 3.2.8 on 2021-10-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_our_team_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_team',
            name='facebook_profile_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='our_team',
            name='linked_in_profile_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='our_team',
            name='skype_profile_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
