# Generated by Django 3.2.8 on 2021-10-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20211018_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions_and_answers',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
