# Generated by Django 3.2.8 on 2021-10-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_questions_and_answers_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions_and_answers',
            name='quetion',
            field=models.CharField(max_length=100),
        ),
    ]
