# Generated by Django 3.2.8 on 2021-10-20 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_questions_and_answers_quetion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecificationTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('index', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Products Specs Title',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='hsn',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mrp',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='ProductSpecificationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proparty', models.CharField(max_length=50)),
                ('values', models.CharField(blank=True, max_length=100, null=True)),
                ('index', models.IntegerField(default=1)),
                ('productSpec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productspecificationtitle')),
            ],
            options={
                'verbose_name_plural': 'Products Specs Desc',
            },
        ),
    ]
