# Generated by Django 3.2.8 on 2021-10-20 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20211020_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecificationtitle',
            name='prodct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
            preserve_default=False,
        ),
    ]
