# Generated by Django 3.2.8 on 2021-10-20 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_product_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productspecificationtitle',
            old_name='prodct',
            new_name='product',
        ),
    ]
