# Generated by Django 3.2.8 on 2021-10-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20211020_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='upload/galary/')),
                ('alt1', models.CharField(blank=True, max_length=150, null=True)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ImageGalary',
        ),
    ]
