# Generated by Django 3.2.8 on 2021-10-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20211020_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallary',
            options={'verbose_name_plural': 'Image Gallary'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Blog'},
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
