# Generated by Django 3.2.6 on 2021-11-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20211027_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
