# Generated by Django 3.2.6 on 2021-11-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
