# Generated by Django 3.2.8 on 2021-11-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_company_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='alt_s1',
            field=models.CharField(blank=True, default='Diamond Laser Cutting Machine', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='alt_s2',
            field=models.CharField(blank=True, default='Diamond Laser Cutting Machine', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='alt_s3',
            field=models.CharField(blank=True, default='Diamond Laser Cutting Machine', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='alt1',
            field=models.CharField(blank=True, default='Diamond Laser Cutting Machine', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='alt2',
            field=models.CharField(blank=True, default='Diamond Laser Cutting Machine', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='alt3',
            field=models.CharField(blank=True, default='Diamond Laser Cutting Machine', max_length=150, null=True),
        ),
    ]
